title               : Van's Horns
url                 : https://vanshorns.com/
baseurl             : /
description         : Evan Yohe's blog about saxophone and saxophone playing.
email               : evan@vansamps.com
author              : Evan Yohe
keywords            : Saxophone, Sax, Saxophone technique, Sax technique, Saxophone practice, Sax practice

# Filtering
except_separator    : "<<>>"
show_drafts         : false
limit_posts         : 0
future              : false
unpublished         : false

# Outputting
permalink           : date
timezone            : America/Los_Angeles
paginate            : 5
paginate_path       : "/writing/page:num"

# Handling Reading
safe                : false
include             : [".htaccess"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", "dockerfile"]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

sass:
  sourcemap         : always
  style             : compact
  sass_dir          : _sass

theme               : null

plugins:
  - jekyll-paginate
  - github-pages
